service: recognize-faces

plugins:
  - serverless-plugin-datadog
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: python3.7
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  stackTags:
    owner: ${param:owner}
  tags:
    owner: ${param:owner}

  # TODO: Check why per function permissions don't work with dd layer
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "rekognition:DetectFaces"
        - "rekognition:SearchFacesByImage"
        - "rekognition:IndexFaces"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "SNS:Publish"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
      Resource: "*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.py
#    - include-me-dir/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**

functions:
  face-detection:
    handler: functions/face_detection.handler
    tags:
      dd_service: face-detection
      dd_env: ${param:ddenv}
      dd_version: "1.0"
    events:
    - http:
        path: detect-faces 
        method: post 
    environment:
      FACE_DETECTION_INDEX_TOPIC: !Ref FaceDetectionIndexTopic
      FACE_SEARCH_ENDPOINT: ${param:face-search-endpoint, 'ENDPOINT_NOT_SET'}
      DD_ENV: ${param:ddenv}
      DD_SERVICE: face-detection
      DD_VERSION: "1.0"
  face-search:
    handler: functions/face_search.handler
    tags:
      dd_service: face-search
      dd_env: ${param:ddenv}
      dd_version: "1.0"
    environment:
      REKOGNITION_COLLECTION_ID: ${param:rekognition-collection-id} 
      DD_ENV: ${param:ddenv}
      DD_SERVICE: face-search
      DD_VERSION: "1.0"
    events:
    - http:
        path: search-faces 
        method: post 
  face-index:
    handler: functions/face_index.handler
    tags:
      dd_service: face-index
      dd_env: ${param:ddenv}
      dd_version: "1.0"
    environment:
      REKOGNITION_COLLECTION_ID: ${param:rekognition-collection-id}
      FACE_DETECTION_PERSIST_TOPIC: !Ref FaceDetectionPersistTopic
      DD_ENV: ${param:ddenv}
      DD_SERVICE: face-index
      DD_VERSION: "1.0"
    events:
    - sns:
        arn: !Ref FaceDetectionIndexTopic
        topicName: FaceDetectionIndexTopic
  persist-metadata:
    handler: functions/persist_metadata.handler
    tags:
      dd_service: persist-metadata
      dd_env: ${param:ddenv}
      dd_version: "1.0"
    environment:
      FACE_DETECTION_DDB_TABLE: !Ref FaceDetectionDDBTable
      DD_ENV: ${param:ddenv}
      DD_SERVICE: persist-metadata
      DD_VERSION: "1.0"
    events:
    - sns:
        arn: !Ref FaceDetectionPersistTopic
        topicName: FaceDetectionPersistTopic

resources:
    # S3
  - ${file(resources/s3-photo-bucket.yml)}
    # SNS Topic Index
  - ${file(resources/sns-topic-index.yml)}
    # SNS Topic Persist
  - ${file(resources/sns-topic-persist.yml)}
    # DynamoDB Table
  - ${file(resources/dynamo-table.yml)}

custom:
    datadog:
        apiKey: ${param:ddApiKey}
